### ISSUE TITLE
pdm tui 没有数据，检查日志发现检查券商系统对接 ERROR:对接失败

### ISSUE THREAD

**Issue by xinmans** [xdusongwei/HODL#3]
```
11-15 23:31:44.291|INFO:启动线程
11-15 23:31:44.306|INFO:检查券商系统对接
11-15 23:31:44.307|ERROR:对接失败
Traceback (most recent call last):
  File "/home/xxx/mydev/HODL/hodl/store.py", line 423, in run
    self.booting_check()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/xxx/mydev/HODL/hodl/store.py", line 32, in booting_check
    raise e
  File "/home/xxx/mydev/HODL/hodl/store.py", line 22, in booting_check
    self.broker_proxy.query_quote()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xxx/mydev/HODL/hodl/proxy/broker_proxy.py", line 47, in query_quote
    return self._query_quote()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/xxx/mydev/HODL/hodl/proxy/broker_proxy.py", line 43, in _query_quote
    raise QuoteScheduleOver
hodl.exception_tools.QuoteScheduleOver

```

**Comment by xdusongwei** [comment]
你买了那个券商的美股行情, 需要在配置文件专门的meta那一节改动设置,
比如你买了futu的,
那么 [[broker_meta.futu]] 这一节配置的
quote_regions, 列表得加上 'US'
券商有很多市场的行情可以提供, 实际上需要考虑你有什么市场的权限才会允许程序去使用那个市场的行情

**Comment by xdusongwei** [comment]
若是运行 tui, 做tui的程序配置需要一节新的配置文件设定
[tui]
manager_url = "https://.../manager.json"
profit_url = "https://.../earning.json"

他们对应的是做服务的那个bot程序的配置的这两项
manager_state_path = ".../manager.json"
earning_json_path = ".../earning.json"

需要自行挂到web服务器的静态目录上
