### ISSUE TITLE
APPL 走富途查询，报错

### ISSUE THREAD

**Issue by xinmans** [xdusongwei/HODL#4]
@classmethod
    def to_tz(cls, symbol: str) -> str:
        if re.match(r'^[56]\d{5}$', symbol):
            tz_offset = '+08:00'
        elif re.match(r'^[013]\d{5}$', symbol):
            tz_offset = '+08:00'
        elif re.match(r'^\d{5}$', symbol):
            tz_offset = '+08:00'
        else:
            raise PrepareError(f'不能转换{symbol}为任何富途证券的时区信息')
        return tz_offset

11-16 00:05:11.538|INFO:启动线程
11-16 00:05:11.555|INFO:检查券商系统对接
11-16 00:05:11.557|ERROR:对接失败
Traceback (most recent call last):
  File "/home/xinmans/mydev/HODL/hodl/store.py", line 423, in run
    self.booting_check()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/store.py", line 32, in booting_check
    raise e
  File "/home/xinmans/mydev/HODL/hodl/store.py", line 22, in booting_check
    self.broker_proxy.query_quote()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/proxy/broker_proxy.py", line 48, in query_quote
    return self._query_quote()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/proxy/broker_proxy.py", line 43, in _query_quote
    raise exc
  File "/home/xinmans/mydev/HODL/hodl/proxy/broker_proxy.py", line 30, in _query_quote
    quote = broker.fetch_quote()
  File "/home/xinmans/mydev/HODL/hodl/broker/base.py", line 379, in wrapper
    raise e
  File "/home/xinmans/mydev/HODL/hodl/broker/base.py", line 373, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/xinmans/mydev/HODL/hodl/broker/futu.py", line 140, in fetch_quote
    tz_offset = self.to_tz(symbol)
  File "/home/xinmans/mydev/HODL/hodl/broker/futu.py", line 132, in to_tz
    raise PrepareError(f'不能转换{symbol}为任何富途证券的时区信息')
hodl.exception_tools.PrepareError: 不能转换AAPL为任何富途证券的时区信息

**Comment by xdusongwei** [comment]
我没买过futu的行情, 可以更新代码, 美股代码可以转换为特定时区了
