### ISSUE TITLE
hodl.exception_tools.PrepareError

### ISSUE THREAD

**Issue by xinmans** [xdusongwei/HODL#7]
11-19 00:13:25.442|WARNING:流程异常: 
11-19 00:13:31.613|ERROR:更新收工状态/持仓/现金/行情时出现错误:
Traceback (most recent call last):
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 375, in on_current
    self.prepare_chip()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 165, in prepare_chip
    chip_count = self.current_chip()
  File "/home/xinmans/mydev/HODL/hodl/trade_mixin.py", line 93, in current_chip
    return self.broker_proxy.query_chips()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/proxy/broker_proxy.py", line 63, in query_chips
    assert isinstance(chips, int)
           ~~~~~~~~~~^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 381, in on_current
    raise error
hodl.exception_tools.PrepareError
11-19 00:13:31.614|WARNING:流程异常:

**Comment by xdusongwei** [comment]
是有非整数碎股么

**Comment by xinmans** [comment]
> 是有非整数碎股么

美股不区分碎股吧
港股有14股赠送的狗东碎股

**Comment by xinmans** [comment]
盘后和夜盘不能支持吗？
现在美股全天候24小时都可以交易。

**Comment by xinmans** [comment]
可以支持下模拟盘成交下单吗？
实盘担心大亏损

**Comment by xdusongwei** [comment]
参考券商模拟盘配置说明填充配置文件吧

**Comment by xinmans** [comment]
脆股都卖了，但是还是报错

11-20 23:28:32.186|WARNING:流程异常: 
11-20 23:28:38.399|ERROR:更新收工状态/持仓/现金/行情时出现错误:
Traceback (most recent call last):
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 368, in on_current
    self.prepare_chip()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 166, in prepare_chip
    chip_count = self.current_chip()
  File "/home/xinmans/mydev/HODL/hodl/trade_mixin.py", line 96, in current_chip
    return self.broker_proxy.query_chips()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/proxy/broker_proxy.py", line 63, in query_chips
    assert isinstance(chips, int)
           ~~~~~~~~~~^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 374, in on_current
    raise error
hodl.exception_tools.PrepareError
11-20 23:28:38.401|WARNING:流程异常:

**Comment by xdusongwei** [comment]
虽然你没提供出配置文件, 没有指出具体所管理的持仓是哪个, 我猜你可能填写的symbol代码并不能在持仓接口中正确对应到你期望的结果.

**Comment by xinmans** [comment]
> 虽然你没提供出配置文件, 没有指出具体所管理的持仓是哪个, 我猜你可能填写的symbol代码并不能在持仓接口中正确对应到你期望的结果.

配置如下，所以意思是symbol = "AAPL"要修改成longport支持的symbol ？

# 每个持仓的部分在 StoreConfig 中定义
[store.AAPL_longport]
region = "US"
currency = "USD"
broker = "longport"
symbol = "AAPL"
trade_strategy = "hodl"
trade_type = "stock"
name = "apple"
enable = true
visible = true
max_shares = 12345
state_file_path = "./state-{broker}-{symbol}-stage{stage}.json"
state_archive_folder = "./hodl/archive-{broker}-{symbol}"
buy_spread_rate = 0.0
sell_spread_rate = 0.004
buy_order_rate = 0.002
sell_order_rate = 0.002
precision = 2
shares_per_unit = 1
booting_check = true
base_price_last_buy = true
base_price_last_buy_days = 21
base_price_day_low = true
base_price_tumble_protect = true
base_price_using_broker = true
tumble_protect_day_range = 7
tumble_protect_rsi = true
tumble_protect_rsi_unlock_limit = 75
tumble_protect_rsi_warning_limit = 25
lock_position = true
price_rate = 1.0
rework_level = 1
market_price_rate = 0.005
sleep_mode = true

**Comment by xdusongwei** [comment]
持仓设置看起来没问题, 可能是broker节的设定关系
你可以直接在根目录 debug broker 对象, 了解连接环境:
```python
from hodl.tools import *
from hodl.broker import *
v = VariableTools()
bc = v.broker_config_dict('longport')
broker = LongPortApi(
    broker_config=bc,
    symbol='AAPL',
    name='',
)
broker.on_init()

print("cash:", broker.query_cash())
print("AAPL chips:", broker.query_chips())
```

**Comment by xinmans** [comment]
> 持仓设置看起来没问题, 可能是broker节的设定关系 你可以直接在根目录 debug broker 对象, 了解连接环境:
> 
> ```python
> from hodl.tools import *
> from hodl.broker import *
> v = VariableTools('/your/config/toml/path')
> bc = v.broker_config_dict('longport')
> broker = LongPortApi(
>     broker_config=bc,
>     symbol='AAPL',
>     name='',
> )
> broker.on_init()
> 
> print("cash:", broker.query_cash())
> print("AAPL chips:", broker.query_chips())
> ```
cash 获取正常，但是query_chips返回空，broker是长桥
```
xinmans@ubuntu-quant:~/mydev/HODL$ pdm x
+----------+----------------------+
| HK       | LV1 Real-time Quotes |
|----------+----------------------|
| US       | Nasdaq Basic         |
|----------+----------------------|
| USOption | LV1 Real-time Quotes |
|----------+----------------------|
| CN       | LV1 Real-time Quotes |
+----------+----------------------+
cash: -13534.56
AAPL chips: None\

```

**Comment by xdusongwei** [comment]
能确定你在这个环境持有苹果股票么

**Comment by xinmans** [comment]
> 能确定你在这个环境持有苹果股票么

是不是还没开市，所以是None？
目前没有持有APPLE，持有AMD

**Comment by xinmans** [comment]
> 能确定你在这个环境持有苹果股票么
AMD测试OK，所以broker是OK的，那问题出在哪里？如何进一步debug，好像日志比较少

xinmans@ubuntu-quant:~/mydev/HODL$ pdm x
+----------+----------------------+
| CN       | LV1 Real-time Quotes |
|----------+----------------------|
| USOption | LV1 Real-time Quotes |
|----------+----------------------|
| US       | Nasdaq Basic         |
|----------+----------------------|
| HK       | LV1 Real-time Quotes |
+----------+----------------------+
cash: -13534.56
AMD chips: 600

**Comment by xinmans** [comment]
同样的配置文件，访问长桥
启动pdm bot后报错
11-22 22:37:22.305|DEBUG:开始处理循环
11-22 22:37:22.305|ERROR:更新状态字典/计划/市场状态/交易系统测试/订单时出现错误:配置的所有broker没有任何可支持该品种获取其对应的市场状态
Traceback (most recent call last):
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 444, in run
    self.prepare_market_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 86, in prepare_market_status
    broker_name, broker_display, market_status = self.current_market_status()
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/xinmans/mydev/HODL/hodl/quote_mixin.py", line 33, in current_market_status
    return self.market_status_proxy.query_status(self.store_config)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/xinmans/mydev/HODL/hodl/proxy/market_status_proxy.py", line 84, in query_status
    raise BrokerMismatchError(f'配置的所有broker没有任何可支持该品种获取其对应的市场状态')
hodl.exception_tools.BrokerMismatchError: 配置的所有broker没有任何可支持该品种获取其对应的市场状态

**Comment by xdusongwei** [comment]
> 同样的配置文件，访问长桥 启动pdm bot后报错 11-22 22:37:22.305|DEBUG:开始处理循环 11-22 22:37:22.305|ERROR:更新状态字典/计划/市场状态/交易系统测试/订单时出现错误:配置的所有broker没有任何可支持该品种获取其对应的市场状态 Traceback (most recent call last): File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 444, in run self.prepare_market_status() ~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 86, in prepare_market_status broker_name, broker_display, market_status = self.current_market_status() ~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/home/xinmans/mydev/HODL/hodl/quote_mixin.py", line 33, in current_market_status return self.market_status_proxy.query_status(self.store_config) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^ File "/home/xinmans/mydev/HODL/hodl/proxy/market_status_proxy.py", line 84, in query_status raise BrokerMismatchError(f'配置的所有broker没有任何可支持该品种获取其对应的市场状态') hodl.exception_tools.BrokerMismatchError: 配置的所有broker没有任何可支持该品种获取其对应的市场状态

需要把密钥去掉的配置看看, 这个讨论没看到完整的配置情况

**Comment by xinmans** [comment]
> > 同样的配置文件，访问长桥 启动pdm bot后报错 11-22 22:37:22.305|DEBUG:开始处理循环 11-22 22:37:22.305|ERROR:更新状态字典/计划/市场状态/交易系统测试/订单时出现错误:配置的所有broker没有任何可支持该品种获取其对应的市场状态 Traceback (most recent call last): File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 444, in run self.prepare_market_status() ~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/home/xinmans/mydev/HODL/hodl/store_hodl.py", line 86, in prepare_market_status broker_name, broker_display, market_status = self.current_market_status() ~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/home/xinmans/mydev/HODL/hodl/quote_mixin.py", line 33, in current_market_status return self.market_status_proxy.query_status(self.store_config) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^ File "/home/xinmans/mydev/HODL/hodl/proxy/market_status_proxy.py", line 84, in query_status raise BrokerMismatchError(f'配置的所有broker没有任何可支持该品种获取其对应的市场状态') hodl.exception_tools.BrokerMismatchError: 配置的所有broker没有任何可支持该品种获取其对应的市场状态
> 
> 
> 
> 需要把密钥去掉的配置看看, 这个讨论没看到完整的配置情况

配置如下，全部换成了长桥，且股票换成了有持仓的AMD
# 根配置在 VariableTools 中定义
manager_state_path = "./manager.json"
earning_json_path = "./earning.json"
db_path = "./data.db"
async_market_status = true
earning_csv_weeks = 6
html_file_path = "./state.html"
html_auto_refresh_time = 300000
log_root = "./logs"

# 每个持仓的部分在 StoreConfig 中定义
[store.AMD_longport]
region = "US"
currency = "USD"
broker = "longport"
symbol = "AMD"
trade_strategy = "hodl"
trade_type = "stock"
name = "amd"
enable = true
visible = true
max_shares = 12345
state_file_path = "./state-{broker}-{symbol}-stage{stage}.json"
state_archive_folder = "./hodl/archive-{broker}-{symbol}"
buy_spread_rate = 0.0
sell_spread_rate = 0.004
buy_order_rate = 0.002
sell_order_rate = 0.002
precision = 2
shares_per_unit = 1
booting_check = true
base_price_last_buy = true
base_price_last_buy_days = 21
base_price_day_low = true
base_price_tumble_protect = true
base_price_using_broker = true
tumble_protect_day_range = 7
tumble_protect_rsi = true
tumble_protect_rsi_unlock_limit = 75
tumble_protect_rsi_warning_limit = 25
lock_position = true
price_rate = 1.0
rework_level = 1
market_price_rate = 0.005
sleep_mode = true

[broker.longport]
app_key = "11"
app_secret = "111"
# 需要指定一个文件位置, 以便存储刷新token
token_path = './longport_accesstoken.toml'
auto_refresh_token = true
trade_env = "SIMULATE" # REAL 真实环境, SIMULATE 模拟环境


[[broker_meta.longport]]
trade_type = 'stock'
share_market_status = false
share_quote = true
market_status_regions = []
quote_regions = ['CN', 'HK', ]
trade_regions = ['US', ]


[tui]
manager_url = "https://192.168.31.90/manager.json"
profit_url = "https://192.168.31.90/earning.json"

**Comment by xdusongwei** [comment]
`share_market_status` 以及 `market_status_regions` 的设置导致的, 可以参考 #1 的模板
